### ISSUE TITLE
Setting Fieldspeed etc.

### ISSUE THREAD

**Issue by punchi21** [Courseplay/Courseplay_FS22#28]
I can't set the Fieldspeed, wont change
And reservespeed only goes between 2 and 5 km/h 

The thing is, this only accurs on an old savegame. On a fresh savegame (same mods) it works without problems

**Comment by hanrahs** [comment]
I had the same issue but on a new game also, both the fieldwork speed and the on field speed are stuck on 5km/h, reverse and turning you could go between 2 and 5km/h. restarting the game made no difference.

**Comment by Alaxsxag** [comment]
same here...

**Comment by Horozor** [comment]
Same. But only with grass mower, combine works fine. 10km/h

**Comment by DTrigger05** [comment]
I currently also have this problem, with the John Deere T560. Have not tested any other vehicles yet.

**Comment by Tensuko** [comment]
What Version did you all use ?

We pushed something with a speed fix.
We need to figure our on what condition the speed gets limited.

**Comment by DTrigger05** [comment]
Originally noted with 7.0.0.1. Problem persists in 7.0.0.3, does not appear to be dependent on a specific vehicle, tried with two others and still limited to 3mph in fieldwork/field speed settings. Running an existing pre-courseplay save.

**Comment by Peiren85** [comment]
> What Version did you all use ?
> 
> We pushed something with a speed fix. We need to figure our on what condition the speed gets limited.

Ich  kann in dem Fall nur für mich sprechen aber ich habe alle Versionen ausprobiert. Also von der 7.0.0.1 bis hin zur 7.0.0.3 . Hab sogar versucht den Mod komplett zu entfernen und dann noch mal neu drauf zu machen ab er keine Besserung. Ging bei mir auch von Anfang an nicht.

**Comment by Horozor** [comment]
7.0.0.1

**Comment by punchi21** [comment]
I used version 7.0.0.1

**Comment by Horozor** [comment]
7.0.0.3 same, 5km/h

**Comment by hanrahs** [comment]
updating to 7.0.0.3 fixed it for me (in the save I was having issues with)

**Comment by Opa-Andre** [comment]
The speed issue in 7.0.0.3 is obviously due to using the wrong variable... I just tested it. My turning speed was set to 15km/h but CP was using 5km/h only. As the "reverse speed" was set to 5km/h (but my tractor didn't need to drive backwards) I set this reverse speed setting to 10 km/h for testing - and from there on, my tractor was driving 10 km/h when changing lanes...

**Comment by geati6783** [comment]
Also have this issue only on John Deere models. X9 1100 and 8R 410

**Comment by Peiren85** [comment]
> updating to 7.0.0.3 fixed it for me (in the save I was having issues with)

Have you possibly done anything differently and if so what to make it work? I still can not set any of the settings to more than 5km / h.

**Comment by Porter76** [comment]
> > updating to 7.0.0.3 fixed it for me (in the save I was having issues with)
> 
> Have you possibly done anything differently and if so what to make it work? I still can not set any of the settings to more than 5km/h.

SAME here

**Comment by FarmerCedric** [comment]
i have the same issue

**Comment by Horozor** [comment]
7.0.0.4 issue still here

**Comment by Tensuko** [comment]
Just becouse we are curious....
Do you have any CruisControl set ?
Or maybe a mod that 'mess arround' with the speeds ?

**Comment by Peiren85** [comment]
> Just becouse we are curious.... Do you have any CruisControl set ? Or maybe a mod that 'mess arround' with the speeds ?

Ich hoffe es ist ok wenn ich in Deutsch antworte weil mein Englisch ist nicht das beste :D 
Was meinst du mit CruiControl?
Hier mal meine Modliste die neben CP aktiv sind:
Auto Drive
Auto Turn Off Turn Lights
Air Hose Connect Sound Script
Heap Preview
HOT Cargo System
Info Nachrichten HUD
Kalkfabrik
Kostenlose Landschaftsbau Tools
Manuelle Plane
Manuelles Ankuppeln
Manuelles Überladen
Maßband
Place Anywhere
Player Superstrenght Light
Pöttinger Impress 125 FC Pro
Realistische Kabinenansicht
Realistische Spielergröße
SIM Dashboard Schnittstelle
Schneidwerk-Fix
VCA
Reduced Maintenance Costs
Vicon FastBale
Paint and TerraForm anywhere

Wenn ich das richtig sehe ist hier nichts dabei was die Geschwindigkeiten beeinflusst.

**Comment by Horozor** [comment]
Just tested 7.0.0.4. 
New game, no mods, only CP all good. 
My savegame, no mods, only CP speed limit for ALL vehicles 5km/h
I think the error persisted in  the game save after using version 7.0.0.1. Now only a new game will help .. (no thanks)

**Comment by pvaiko** [comment]
Please, check your Cruise Control (Tempomat) setting, is it accidentally set to 5, or some lower speed?
![image](https://user-images.githubusercontent.com/2379521/147395876-53d3b852-b166-471e-a861-059679da95e3.png)

**Comment by Horozor** [comment]
Cruise Control set to maximum, 63 for Fendt 900vario
![image](https://user-images.githubusercontent.com/37561569/147395923-b4969be4-f702-45ed-9bf2-f1b89928c462.png)
But in settings can change only turn and reverse speed from 2 to 5 km/h
![image](https://user-images.githubusercontent.com/37561569/147395945-5a17c267-0867-4d56-a94b-448b44d9cb2f.png)

**Comment by Peiren85** [comment]
Ich habe das mit dem Tempomat auch gerade nochmal gecheckt und dabei war aus versehen mein MAN LKW Gewählt. Bei diesem kann ich die Settings ändern. In meinem Topliner 4090H, Axion 830 und dem Maxxum CVX 125 bleibt alles beim alten. Tempomat ist bei allen auf Maximum gesetzt und ist auch nicht aktiviert.

**Comment by Horozor** [comment]
@pvaiko @Tensuko 
I found where is problem. In the savegame folder is file vehicles.xml. If i delete this file, all my vehicles disappear but new buyed vehicles have no problem with speed limit
It's my file. check this please
[vehicles.xml](https://gist.github.com/Horozor/845f880bc8210183a13d2312d9b120c5)

**Comment by Naiszen** [comment]
Ich habe auch das Problem, und bin inzwischen auch auf das Savegame gestoßen, nur die Datei konnte ich nicht Identifizieren.
Dieses Problem habe ich auch nur in mein Savegame, welche ich seit Freitag benutzt habe. andere Savegames sind davon nicht betroffen auch wenn ich einen neuen spielstand hab, ist der Fehler nicht vorhanden.

**Comment by Naiszen** [comment]
hab für mich scheinbar die Lösung. Ich habe die Förderband Geräte verkauft. Danach konnte ich die Geschwindigkeit wieder hoch stellen...    Ja diese Förderband teile haben ja auch eine Max geschwindigkeit von 5 km/h und beim tabben werden diese übersprungen, daher kam ich auch erst so spät drauf... nun hoffe ich mal das ich dadurch vielleicht auch bei den entwicklern etwas helfen kann ;)

**Comment by reztierk** [comment]
@Tensuko Hmmm, just doing some investigating based on my findings versus a friends (my speed is stuck at 13 for all and his is 5 for all). @Horozor pointed out the vehicles.xml, which has "<drivable cruiseControl="13" cruiseControlReverse="13"/>" under my skid steer. My hunch is all vehicles are being limited to the cruise control speed of the slowest vehicle you own.

**Comment by Peiren85** [comment]
> hab für mich scheinbar die Lösung. Ich habe die Förderband Geräte verkauft. Danach konnte ich die Geschwindigkeit wieder hoch stellen... Ja diese Förderband teile haben ja auch eine Max geschwindigkeit von 5 km/h und beim tabben werden diese übersprungen, daher kam ich auch erst so spät drauf...

Genau das hilft. Ich habe meine Förderbänder nun auch verkauft. das Spiel gespeichert und neu geladen und siehe da, die Settings funktionieren wie sie sollen. Ich habe auch versucht den Fehler in einem neuen Spielstand zu reproduzieren. Ich habe diese Förderbänder gekauft und dann das savegame neu geladen mit CP aber es hat dennoch alles funktioniert. Auch in dem savegame, wo der Fehler auftrat, habe ich nach dem Verkauf der Förderbänder diese noch einmal gekauft, gespeichert und savegame neu geladen und weiterhin hat alles funktioniert. Fehler war in der 7.0.0.4 also nicht reproduzierbar. Scheint sich also von einer vorherigen Version fest gefressen zu haben. Man kann die Förderbänder, allem Anschein nach, also in der aktuellen Version nutzen. Muss sie allerdings einmal verkaufen und neu kaufen. Ich lasse sie erst einmal verkauft denn ich brauche sie derzeit eh nicht :D

**Comment by hanrahs** [comment]
> > updating to 7.0.0.3 fixed it for me (in the save I was having issues with)
> 
> Have you possibly done anything differently and if so what to make it work? I still can not set any of the settings to more than 5km/h.

Not sure if still interested, but I didn't do anything else other than up date to 7.0.0.3, not sure why it worked. I had sold all vehicles when I began the game and only had a JD X9 1100 and a truck and trailer. All mods are from the in game modhub except courseplay and autodrive. 

While it fixed the initial speed problem, I couldn't get any new course to work in any other field after that- it would attempt to start but just do circles... probably my error - but I couldn't work out how to fix that one.

ended up starting a new save now and it is working fine so far

**Comment by Porter76** [comment]
The same for me.
Courseplay is apparently always aimed at the slowest vehicle in your fleet. If you have the conveyor belt this is 5km / h. If you have the forklift 20km / h ... etc. Sell vehicles and restart the game. This helps!

**Comment by rLy07** [comment]
Seems like there's a typo in line 15 in  Courseplay_FS22/scripts/ai/parameters/AIParameterSpeedSetting.lua 
Using math.max instead of math.min in AIParameterSpeedSetting.getMaxSpeed function fixes this. I'm able to change the max working speed while owning conveyors.

**Comment by Naiszen** [comment]
Hab noch beim Düngerstreuer, das der immernoch nicht über 5 km/h geht. Aber die Einstellungen kann und hab ich deutlich höher eingestellt. also das einstellen geht, auch Tempomart ist auf max, aber trotzdem fährt er nicht über 5 km/h... alle anderen Fahrzeuge funktionieren sehr gut. nur der kleine Düngerstreuer nicht....

**Comment by Tensuko** [comment]
> also das einstellen geht, auch Tempomart ist auf max, aber trotzdem fährt er nicht über 5 km/h... alle anderen Fahrzeuge funktionieren sehr gut. nur der kleine Düngerstreuer nicht....

Also wenn wir eine gewisse Geschwindigkeit erlauben, aber das Gerät nicht schneller fährt, könnte es auch am Tool liegen. Hast du in diese Richtung mal geschaut ? Vlt einen anderen Streuer oder so ?

**Comment by Tensuko** [comment]
Can you pls try the new Version 7.0.0.5 ?
It might be just an temporary fix, but at least your tools can work at their correct speed.

**Comment by DTrigger05** [comment]
I did have conveyors, so bring limited to the slowest vehicle seems to apply to me too.

That said, 7.0.0.5 does work for me.

**Comment by Tensuko** [comment]
Seems to be fixed now.
